PythonVersion="3.9.7"
packagedir=".python_packages/lib/site-packages"
OperationId="|BvKh4KWpvo8=.509e4a41_"
SourceDirectoryInBuildContainer="/tmp/zipdeploy/extracted"
PlatformName="python"
CompressDestinationDir="false"
